### ISSUE TITLE
We need a name

### ISSUE THREAD

**Issue by rbarker12** [corkin/event-site#17]
How we can pare down: Everyone needs to dump their names suggestions into one full file and we can pare down from there. We then triage what does and does not "spark joy." Email me your names and I'll get this organized. barker.rich@gmail.com

**Comment by kfwojton** [comment]
We can just use this as a place to post names.

**Comment by rbarker12** [comment]
Clasp
Hive
PostHub
BlastHouse
OnBlast
Arugula
Rocket Salad (wiki says this is another name for arugula lol just threw it on)
Feis (pronounced Fesh, Irish name for festival)
BlockParty

**Comment by rbarker12** [comment]
Here are Corey's 

yupp
hiphip
city pocket
neighborhood pockets
good neighborhood
umbrella
backyard
backyarder
jamboree
jamboree lab
muster

**Comment by rbarker12** [comment]
CleveHub
ClevHub

**Comment by kfwojton** [comment]
wonderjuncture 
escapade

**Comment by rbarker12** [comment]
YUPP
