### ISSUE TITLE
event submission form - (full stack)

### ISSUE THREAD

**Issue by rbarker12** [corkin/event-site#9]
![Screenshot from 2019-03-30 12-11-28](https://user-images.githubusercontent.com/48738100/55278619-12ecad80-52e5-11e9-9d8f-c622cb924bde.png)

**Comment by kfwojton** [comment]
very cool. I think we can re format that. Have a look at https://docs.djangoproject.com/en/2.1/topics/forms/modelforms/ , you will have to render the form elements and then also format the form elements. I would suggest looking at the models file to see the elements you can bring in.

**Comment by kfwojton** [comment]
This is covered by @corkin PR
